"""GitHub integration: PR creation via PyGithub.

Creates pull requests with the optimized code, diff summary,
and validation results as the PR body.

Owner: ___
Status: NOT STARTED
Depends on: PyGithub, models/types.py
"""

from __future__ import annotations

from backend.models.types import ValidationResult


def create_optimization_pr(
    repo_name: str,
    branch_name: str,
    file_path: str,
    original_source: str,
    optimized_source: str,
    validation: ValidationResult,
    base_branch: str = "main",
) -> str:
    """Create a GitHub PR with the optimized code.

    Returns the PR URL.

    Owner: ___
    Status: NOT STARTED
    Depends on: PyGithub, GITHUB_TOKEN env var
    """
    # TODO: Authenticate with PyGithub using os.environ["GITHUB_TOKEN"]
    # TODO: Get repo object
    # TODO: Create new branch from base_branch
    # TODO: Update file content on the new branch
    # TODO: Build PR body with:
    #   - Summary of improvements from validation.improvements
    #   - Before/after metrics comparison table
    #   - Big O change if applicable
    #   - Test results summary
    # TODO: Create PR with gh.create_pull()
    # TODO: Return PR URL
    pass


def format_pr_body(validation: ValidationResult) -> str:
    """Format a markdown PR body from validation results.

    Owner: ___
    Status: NOT STARTED
    Depends on: models/types.py
    """
    # TODO: Build markdown with ## sections
    # TODO: Include improvements list, vetoes, metrics tables
    # TODO: Add "Generated by AI Agent Pipeline" footer
    pass
